name: foundations-of-is-class
dependencies:
  - ca-certificates
  - certifi
  - libffi
  - ncurses
  - openssl
  - pip
  - python=3.8
  - readline
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
    - cycler
    - fonttools
    - kiwisolver
    - matplotlib
    - networkx
    - numpy
    - packaging
    - pillow
    - pyparsing
    - python-dateutil
    - scipy
    - six
